<div class="row">
    <div class="card">
        <div class="card-header" style="text-align:center">QUIZ
        </div>
        <div class="card-body">
            <div class="modal-body no-padding">
                <div class="row">
                    <div class="col-12">
                        <form id="form">
                            <div id="divForm"></div>
                            <div class="form-row">
                                <button type="button" onclick="nextPergunta()" class="btn btn-success">Próximo</button>
                            </div>
                        </form>
                    </div>
                </div>
                <br>
                <div class="col">
                    <div class="footer">
                        <div id="message" class="alert alert-danger d-none">teste</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<script>

    var message = document.getElementById('message');
    var message2 = document.getElementById('message2');
    var form = document.getElementById('form');
    let total = 1;
    let partial = 0;
    let index = 0;
    let arrayPerguntas = <?= $perguntas ?>;
    let perguntaCount = 0;
    let arrayRespostas = [];

    function openModal(id) {
        document.getElementById('message2').classList.add('d-none');
        form.reset();
        $("#userId").val(id);
        if (id > 0) {
            showLoading();
            $("#file").attr('required', false);
            fetch(`<?= BASEURL ?>api/usuario/` + id, {
                method: 'GET',
                credentials: "same-origin",
                header: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                }
            }).then(response => {
                response.json().then(json => {
                    let user = json.message[0];
                    $("#name").val(user.name);
                    $("#email").val(user.email);
                    $("#phone").val(formatPhoneNumber(user.phone));
                    closeLoading();
                });
            });
        }
        $("#modal").modal('show');
    }

    function resetForm() {
        $("#nameFilter").val('');
        $("#emailFilter").val('');
        index = 0;
        partial = 0;
        total = 1;
        $("#userTable tbody").empty();
        getUsers();
    }

    function createForm() {
        let pergunta = arrayPerguntas[perguntaCount];
        let div = document.getElementById('divForm');
        div.innerHTML = '';
        let html = `
                            <div class="form-group col-md-12">
                                <label for="descricao">Pergunta</label><br>
                                <span>${pergunta['descricao']}</span>
                            </div>
                            <div class="form-group col-md-12">
                                <input type="radio" name="alternativa" id="alternativa1" value="1">
                                <span>${pergunta['alternativa1']}</span>
                            </div>
                            <div class="form-group col-md-12">
                                <input type="radio" name="alternativa" id="alternativa2" value="2">
                                <span>${pergunta['alternativa2']}</span>
                            </div>
                            <div class="form-group col-md-12">
                                <input type="radio" name="alternativa" id="alternativa3" value="3">
                                <span>${pergunta['alternativa3']}</span>
                            </div>
                            <div class="form-group col-md-12">
                                <input type="radio" name="alternativa" id="alternativa4" value="4">
                                <span>${pergunta['alternativa4']}</span>
                            </div>
                            <div class="form-group col-md-12">
                                <input type="radio" name="alternativa" id="alternativa5" value="5">
                                <span>${pergunta['alternativa5']}</span>
                            </div>

        `;
        div.innerHTML = html;
    }

    function nextPergunta() {
        let value = getRadioValue('alternativa');
        if(value == undefined) return;
        arrayRespostas[perguntaCount] = value;
        perguntaCount++;
        if(arrayRespostas.length === 20) {
            endQuiz();
            return;
        }
        createForm();
    }

    function endQuiz() {
        showLoading();
        let data = formDataToJson('form');
        data.quizId = '<?= $quiz->getId() ?>';
        data.respostas = arrayRespostas;
        data.userId = <?= $user->getId() ?>;
        fetch(`<?= BASEURL ?>api/quiz`, {
            method: 'POST',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data),
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                if(json.status == 'ok') {
                    alert(json.message);
                    setTimeout(function () {
                        window.location.href = "<?= BASEURL ?>quiz/resultados/";
                    }, 1500);
                }
            });
        });
    }

    function getRadioValue(theRadioGroup)
    {
        var elements = document.getElementsByName(theRadioGroup);
        for (var i = 0, l = elements.length; i < l; i++)
        {
            if (elements[i].checked)
            {
                return elements[i].value;
            }
        }
    }

    function changeMessageType(type, id) {
        let message = document.getElementById(id);
        if (type === 'ok') {
            message.classList.remove('alert-danger');
            message.classList.remove('d-none');
            message.classList.add('alert-info');
        }

        if (type === 'error') {
            message.classList.remove('alert-info');
            message.classList.remove('d-none');
            message.classList.add('alert-danger');
        }
    }

    function generateTableBody(json) {
        let icons = `<i class="fa fa-pencil text-info" title="Editar ${json.name}" onclick="openModal(${json.id})"></i> `;
        icons += `<i class="fa fa-times text-danger" title="Deletar ${json.name}" onclick="removeUser(${json.id})"></i> `;
        return `
            <tr>
                <td class="text-center">${json.name}</td>
                <td class="text-center">${json.email}</td>
                <td class="text-center">${formatPhoneNumber(json.phone)}</td>
                <td class="text-center">${icons}</td>
            </tr>
        `;
    }

    function filter() {
        $("#userTable tbody").empty();
        index = 0;
        total = 1;
        partial = 0;
        getUsers();
    }

    function formatPhoneNumber(phoneNumberString) {
        var cleaned = ('' + phoneNumberString).replace(/\D/g, '');
        var match = cleaned.match(/^(\d{2})(\d{5})(\d{4})$/);
        if (match) {
            return '(' + match[1] + ') ' + match[2] + '-' + match[3];
        }
        return '';
    }

    function getUsers() {
        showLoading();
        let name = $("#nameFilter").val();
        let email = $("#emailFilter").val();
        fetch(`<?= BASEURL ?>api/cadastros/aluno/?name=${name}&email=${email}`, {
            method: 'GET',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                total = json.total;
                partial += json.partial;
                $("#total").text(total);
                $("#partial").text(partial);
                let users = json.message;
                let usersHtml = users.map(generateTableBody);
                $("#userTable tbody").append(usersHtml);
            });
        });
    }

    function removeUser(id) {
        showLoading();
        fetch(`<?= BASEURL ?>api/usuario/` + id, {
            method: 'DELETE',
            credentials: "same-origin",
            header: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                changeMessageType(json.status, 'message');
                message.innerText = json.message;
                if (json.status == 'ok') filter();
            });
        });
    }

    form.addEventListener(`submit`, e => {
        e.preventDefault();
        showLoading();
        let data = formDataToJson('form');
        fetch(`<?= BASEURL ?>api/cadastros/pergunta`, {
            method: 'POST',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then(response => {
            response.json().then(json => {
                changeMessageType(json.status, 'message');
                message.innerText = json.message;
                closeLoading();
                if (json.status == 'ok') {
                    setTimeout(function () {
                        window.location.href = "<?= BASEURL ?>cadastros/pergunta/";
                    }, 2000);
                }
            });
        });
    });

    $(document).ready(function () {
        createForm(0);
    });

</script>