<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8"/>
    <!--    <link rel="icon" href="--><? //= BASEURL ?><!--assets/img/logo.png">-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>LogiQuizz</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no"
          name="viewport"/>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="<?= BASEURL ?>assets/css/now-ui-dashboard.css?v=<?= time() ?>" rel="stylesheet"/>
    <link href="<?= BASEURL ?>assets/css/bootstrap.min.css?v=<?= time() ?>" rel="stylesheet"/>
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/dataTables.bootstrap4.min.css"/>
    <link href="<?= BASEURL ?>assets/css/style.css?v=<?= time() ?>" rel="stylesheet"/>
    <script src="<?= BASEURL ?>assets/js/core/jquery.min.js"></script>
</head>

<body>
<div class="wrapper">
    <div class="sidebar" data-color="lightgray">
        <div class="logo pt-4 px-5 text-center">
            <a href="#">
                <img src=""/>
            </a>
        </div>
        <div class="sidebar-wrapper" id="sidebar">
            <ul class="nav title">
                <li>
                    <a href="<?= BASEURL ?>">Home
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <?php if ($user->getTipoUsuario() == 1): ?>
                    <li>
                        <a href="<?= BASEURL ?>cadastros/pergunta">Perguntas
                            <i class="fa fa-question"></i>
                        </a>
                    </li>
                    <li>
                        <a href="<?= BASEURL ?>cadastros/quiz">Criar Quiz
                            <i class="fa fa-user"></i>
                        </a>
                    </li>
                    <li>
                        <a href="<?= BASEURL ?>quiz/resultados">Resultados dos Alunos
                            <i class="fa fa-user"></i>
                        </a>
                    </li>
<!--                    <li>-->
<!--                        <a href="--><?//= BASEURL ?><!--">Visualizar Quiz Criados-->
<!--                            <i class="fa fa-user"></i>-->
<!--                        </a>-->
<!--                    </li>-->
                <?php endif; ?>
                <?php if ($user->getTipoUsuario() == 0): ?>
                    <li>
                        <a href="<?= BASEURL ?>quiz/">Jogar Quiz
                            <i class="fa fa-user"></i>
                        </a>
                    </li>
                    <li>
                        <a href="<?= BASEURL ?>quiz/resultados/">Visualizar Resultados
                            <i class="fa fa-user"></i>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
    <div class="main-panel" id="main-panel">
        <nav class="navbar navbar-expand-lg navbar-transparent bg-secondary navbar-absolute">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <div class="navbar-toggler">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <span class="navbar-brand">Olá, <?= $user->getName()?>!</span>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                        aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-end" id="navigation">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="<?= BASEURL ?>logout"><i class="fa fa-power-off"></i>Sair</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


        <div class="panel-header panel-header-sm"></div>
        <div class="content"

        <?php if (\App\Helpers\Session::get('errorMsg')): ?>
            <div class="row mt-5">
                <div class="col">
                    <div class="alert alert-danger"><?= \App\Helpers\Session::get('errorMsg') ?></div>
                </div>
            </div>
            <?php \App\Helpers\Session::forgot('errorMsg'); ?>
        <?php endif; ?>

