<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8"/>
    <!--    <link rel="icon" href="--><?//= BASEURL ?><!--assets/img/logo.png">-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>LogiQuizz</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no"
          name="viewport"/>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="<?= BASEURL ?>assets/css/now-ui-dashboard.css?v=<?= time() ?>" rel="stylesheet"/>
    <link href="<?= BASEURL ?>assets/css/bootstrap.min.css?v=<?= time() ?>" rel="stylesheet"/>
    <link rel="stylesheet" href="<?= BASEURL ?>assets/css/dataTables.bootstrap4.min.css"/>
    <link href="<?= BASEURL ?>assets/css/style.css?v=<?= time() ?>" rel="stylesheet"/>
    <script src="<?= BASEURL ?>assets/js/core/jquery.min.js"></script>
</head>

<div class="row">
    <div class="card">
        <div class="card-header" style="text-align:center">CADASTRO DE USUÁRIO
        </div>
        <div class="card-body">
            <div class="modal-body no-padding">
                <form id="userForm" method="POST" enctype="multipart/form-data">
                    <div class="modal-body">
                        <div class="row">
                            <div class="col">
                                <input type="hidden" id="userId" name="userId">
                                <div class="form-group">
                                    <label for="name">Nome</label>
                                    <input type="text" id="name" name="name" placeholder="Informe o nome" required
                                           class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="tipo">Tipo</label>
                                    <select id="tipo" name="tipo" required class="form-control" onchange="changeTipo()">
                                        <option value="0">Aluno</option>
                                        <option value="1">Professor</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="text" id="email" name="email" placeholder="Informe o e-mail" required
                                           class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="password">Senha</label>
                                    <input type="password" id="password" name="password" placeholder="Informe a senha" required
                                           class="form-control">
                                </div>
                                <div class="form-group" id="divMatricula">
                                    <label for="matricula">Matricula</label>
                                    <input type="text" id="matricula" class="form-control" name="matricula"
                                           placeholder="Matricula">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col">
                            <div id="message" class="alert alert-success d-none">teste</div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-info float-right" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-success">Cadastrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>

    var message = document.getElementById('message');
    var message2 = document.getElementById('message2');
    var form = document.getElementById('userForm');
    let total = 1;
    let partial = 0;
    let index = 0;

    function openModal(id) {
        document.getElementById('message2').classList.add('d-none');
        form.reset();
        $("#userId").val(id);
        if (id > 0) {
            showLoading();
            $("#file").attr('required',false);
            fetch(`<?= BASEURL ?>api/usuario/` + id, {
                method: 'GET',
                credentials: "same-origin",
                header: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                }
            }).then(response => {
                response.json().then(json => {
                    let user = json.message[0];
                    $("#name").val(user.name);
                    $("#email").val(user.email);
                    //$("#phone").val(formatPhoneNumber(user.phone));
                    closeLoading();
                });
            });
        }
        $("#modal").modal('show');
    }

    function resetForm() {
        $("#nameFilter").val('');
        $("#emailFilter").val('');
        index = 0;
        partial = 0;
        total = 1;
        $("#userTable tbody").empty();
        getUsers();
    }

    function changeMessageType(type, id) {
        let message = document.getElementById(id);
        if (type === 'ok') {
            message.classList.remove('alert-danger');
            message.classList.remove('d-none');
            message.classList.add('alert-info');
        }

        if (type === 'error') {
            message.classList.remove('alert-info');
            message.classList.remove('d-none');
            message.classList.add('alert-danger');
        }
    }

    function generateTableBody(json) {
        let icons = `<i class="fa fa-pencil text-info" title="Editar ${json.name}" onclick="openModal(${json.id})"></i> `;
        icons += `<i class="fa fa-times text-danger" title="Deletar ${json.name}" onclick="removeUser(${json.id})"></i> `;
        return `
            <tr>
                <td class="text-center">${json.name}</td>
                <td class="text-center">${json.email}</td>
                <td class="text-center">${icons}</td>
            </tr>
        `;
    }

    function filter() {
        $("#userTable tbody").empty();
        index = 0;
        total = 1;
        partial = 0;
        getUsers();
    }

    function changeTipo() {
        document.getElementById('divMatricula').classList.add('d-none');
        var tipo = $("#tipo").val();
        if(tipo == '0') {
            document.getElementById('divMatricula').classList.remove('d-none');
        }
    }

    /*function formatPhoneNumber(phoneNumberString) {
        var cleaned = ('' + phoneNumberString).replace(/\D/g, '');
        var match = cleaned.match(/^(\d{2})(\d{5})(\d{4})$/);
        if (match) {
            return '(' + match[1] + ') ' + match[2] + '-' + match[3];
        }
        return '';
    }*/

    function getUsers() {
        showLoading();
        let name = $("#nameFilter").val();
        let email = $("#emailFilter").val();
        fetch(`<?= BASEURL ?>api/cadastros/aluno/` + 0, {
            method: 'GET',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                total = json.total;
                partial += json.partial;
                $("#total").text(total);
                $("#partial").text(partial);
                let users = json.message;
                let usersHtml = users.map(generateTableBody);
                $("#userTable tbody").append(usersHtml);
            });
        });
    }

    function removeUser(id) {
        showLoading();
        fetch(`<?= BASEURL ?>api/usuario/` + id, {
            method: 'DELETE',
            credentials: "same-origin",
            header: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                changeMessageType(json.status, 'message2');
                message.innerText = json.message;
                if(json.status == 'ok') filter();
            });
        });
    }

    form.addEventListener(`submit`, e => {
        e.preventDefault();
        showLoading();
        let data = formDataToJson('userForm');
        fetch(`<?= BASEURL ?>api/cadastros/usuario/`, {
            method: 'POST',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                message.innerText = json.message;
                changeMessageType(json.status, 'message');
                if(json.status == 'ok') {
                    setTimeout(function () {
                        window.location.href = "<?= BASEURL ?>/login";
                    }, 1800);
                }
            });
        });
    });

    $(document).ready(function () {
        getUsers();
    });

</script>