<div class="row">
    <div class="card">
        <div class="card-header" style="text-align:center">CADASTRO DE QUIZ
            <div class="form-row float-right">
                <a href="<?= BASEURL ?>cadastros/novo-quiz" class="btn btn-info">Quiz <i class="fa fa-plus"></i></a>
            </div>
        </div>

        <div class="card-body">
            <h5>Busca de Quizes</h5>
            <div class="modal-body no-padding">
                <div class="row">
                    <div class="col-12">
                        <form id="filter">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="dificuldadeFilter">Dificuldade</label>
                                    <select type="text" id="dificuldadeFilter" name="dificuldadeFilter" class="form-control">
                                        <option value="">Selecione...</option>
                                        <option value="Facil">Fácil</option>
                                        <option value="Medio">Médio</option>
                                        <option value="Dificil">Difícil</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-row">
                                <button type="button" class="btn btn-success" onclick="resetForm()">Limpar</button>
                                <button type="button" class="btn btn-info" onclick="filter()">Filtrar</button>
                            </div>
                        </form>
                        <br>
                        <h5>Lista de Quizes Cadastradas</h5>
                        Exibindo <span id="partial"></span> de <span id="total"></span>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-12">
                        <table id="userTable" class="table table-striped table-bordered">
                            <thead>
                            <th class="text-center">ID</th>
                            <th class="text-center">Quiz</th>
                            <th class="text-center">Dificuldade</th>
                            <th class="text-center">Ações</th>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <div class="col">
                        <div class="footer">
                            <div id="message" class="alert alert-danger d-none">teste</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Modal-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle">Cadastro de Usuário</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times</span>
                </button>
            </div>
            <form id="userForm" method="POST" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <input type="hidden" id="userId" name="userId">
                            <div class="form-group">
                                <label for="name">Nome</label>
                                <input type="text" id="name" name="name" placeholder="Nome" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="tipo">Tipo</label>
                                <select id="tipo" name="tipo" required class="form-control">
                                    <option value="0">Aluno</option>
                                    <option value="1">Professor</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" id="email" name="email" placeholder="Email" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password">Senha</label>
                                <input type="password" id="password" name="password" placeholder="Senha" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="matricula">Matricula</label>
                                <input type="text" id="matricula" class="form-control" name="matricula"
                                       placeholder="Matricula">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-info float-right" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Cadastrar</button>
                </div>
            </form>
            <div class="col">
                <div class="footer">
                    <div id="message2" class="mt-2 alert alert-danger d-none">teste</div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    var message = document.getElementById('message');
    var message2 = document.getElementById('message2');
    var form = document.getElementById('userForm');
    let total = 1;
    let partial = 0;
    let index = 0;

    function openModal(id) {
        document.getElementById('message2').classList.add('d-none');
        form.reset();
        $("#userId").val(id);
        if (id > 0) {
            showLoading();
            $("#file").attr('required',false);
            fetch(`<?= BASEURL ?>api/usuario/` + id, {
                method: 'GET',
                credentials: "same-origin",
                header: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                }
            }).then(response => {
                response.json().then(json => {
                    let user = json.message[0];
                    $("#name").val(user.name);
                    $("#email").val(user.email);
                    //$("#phone").val(formatPhoneNumber(user.phone));
                    closeLoading();
                });
            });
        }
        $("#modal").modal('show');
    }

    function resetForm() {
        $("#dificuldadeFilter").val('');
        $("#userTable tbody").empty();
        getUsers();
    }

    function changeMessageType(type, id) {
        let message = document.getElementById(id);
        if (type === 'ok') {
            message.classList.remove('alert-danger');
            message.classList.remove('d-none');
            message.classList.add('alert-info');
        }

        if (type === 'error') {
            message.classList.remove('alert-info');
            message.classList.remove('d-none');
            message.classList.add('alert-danger');
        }
    }

    function generateTableBody(json) {
        let icons = `<i class="fa fa-pencil text-info" title="Editar ${json.name}"></i> `;
        icons += `<i class="fa fa-times text-danger" title="Deletar ${json.name}"></i> `;
        return `
            <tr>
                <td class="text-center">${json.id}</td>
                <td class="text-center">${json.name}</td>
                <td class="text-center">${json.dificuldade}</td>
                <td class="text-center">${icons}</td>
            </tr>
        `;
    }

    function filter() {
        $("#userTable tbody").empty();
        index = 0;
        total = 1;
        partial = 0;
        getUsers();
    }

    function getUsers() {
        showLoading();
        let dificuldade = $("#dificuldadeFilter").val();
        fetch(`<?= BASEURL ?>api/quiz/?dificuldade=${dificuldade}`, {
            method: 'GET',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                total = json.total;
                partial += json.total;
                $("#total").text(total);
                $("#partial").text(total);
                let users = json.message;
                let usersHtml = users.map(generateTableBody);
                $("#userTable tbody").append(usersHtml);
            });
        });
    }

    function removeUser(id) {
        showLoading();
        fetch(`<?= BASEURL ?>api/usuario/` + id, {
            method: 'DELETE',
            credentials: "same-origin",
            header: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                changeMessageType(json.status, 'message2');
                message.innerText = json.message;
                if(json.status == 'ok') filter();
            });
        });
    }

    form.addEventListener(`submit`, e => {
        e.preventDefault();
        showLoading();
        let data = formDataToJson('userForm');
        fetch(`<?= BASEURL ?>api/cadastros/usuario/`, {
            method: 'POST',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then(response => {
            response.json().then(json => {
                changeMessageType(json.status, 'message2');
                message2.innerText = json.message;
                closeLoading();
                if(json.status == 'ok') {
                    $("#userTable tbody").empty();
                    getUsers();
                    setTimeout(function () {
                        $("#modal").modal('hide');
                    }, 3000);
                }
            });
        });
    });

    //form.addEventListener('submit', e => {
    //    e.preventDefault();
    //    showLoading();
    //    let formData = formDataToJson('userForm');
    //    let method = 'POST';
    //    if(formData.userId > 0) method = 'PUT';
    //    fetch(`<?//= BASEURL ?>//usuario/`, {
    //        method: 'POST',
    //        credentials: "same-origin",
    //        headers: {
    //            'Accept': 'application/json',
    //            'Content-Type': 'application/json',
    //        },
    //        body: JSON.stringify(formData),
    //    }).then(response => {
    //        response.json().then(json => {
    //            closeLoading();
    //            changeMessageType(json.status, 'message2');
    //            message2.innerText = json.message;
    //            if (json.status === 'ok') {
    //                $("#modal").modal('hide');
    //                filter();
    //            }
    //        });
    //    });
    //});

    $(document).ready(function () {
        getUsers();
    });

</script>