<div class="row">
    <div class="card">
        <div class="card-header">Usuários
            <div class="form-row float-right">
                <button type="button" onclick="openModal(0)" class="btn btn-info">Usuário <i class="fa fa-plus"></i></button>
            </div>
        </div>

        <div class="card-body">
            <div class="modal-body no-padding">
                <div class="row">
                    <div class="col-12">
                        <form id="filter">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="nameFilter">Nome</label>
                                    <input type="text" id="nameFilter" name="nameFilter" class="form-control"
                                           placeholder="Nome">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="emailFilter">Email</label>
                                    <input type="text" id="emailFilter" name="emailFilter" class="form-control"
                                           placeholder="Email">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="emailFilter">Tipo Usuário</label>
                                    <input type="text" id="tipoUserFilter" name="tipoUserFilter" class="form-control"
                                           placeholder="Tipo Usuário">
                                </div>
                            </div>
                            <div class="form-row">
                                <button type="button" class="btn btn-success" onclick="resetForm()">Limpar</button>
                                <button type="button" class="btn btn-info" onclick="filter()">Filtrar</button>
                            </div>
                        </form>
                        Exibindo <span id="partial"></span> de <span id="total"></span>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-12">
                        <table id="userTable" class="table table-striped table-bordered">
                            <thead>
                            <th class="text-center">Foto</th>
                            <th class="text-center">Nome</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Fone</th>
                            <th class="text-center">Ações</th>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <div class="col">
                        <div class="footer">
                            <div id="message" class="alert alert-danger d-none">teste</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Modal-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle">Cadastro Usuário</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times</span>
                </button>
            </div>
            <form id="userForm" method="POST" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <input type="hidden" id="userId" name="userId">
                            <div class="form-group">
                                <label for="name">Nome</label>
                                <input type="text" id="name" name="name" placeholder="Nome" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" id="email" name="email" placeholder="Email" required
                                       class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="phone">Telefone</label>
                                <input type="text" id="phone" class="form-control" name="phone"
                                       placeholder="(__)_____-____" data-mask="(99) 99999-9999">
                            </div>
                            <div class="form-row">
                                <div class="col-md-3">
                                    <label class="btn" style="margin-top: 5px" for="file">
                                        <input class="" id="file" type="file" required
                                               name="file">
                                        <span id="file"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-info float-right" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Cadastrar</button>
                </div>
            </form>
            <div class="col">
                <div class="footer">
                    <div id="message2" class="mt-2 alert alert-danger d-none">teste</div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    var message = document.getElementById('message');
    var message2 = document.getElementById('message2');
    var form = document.getElementById('userForm');
    let total = 1;
    let partial = 0;
    let index = 0;

    function openModal(id) {
        document.getElementById('message2').classList.add('d-none');
        form.reset();
        $("#userId").val(id);
        if (id > 0) {
            showLoading();
            $("#file").attr('required',false);
            fetch(`<?= BASEURL ?>api/usuario/` + id, {
                method: 'GET',
                credentials: "same-origin",
                header: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                }
            }).then(response => {
                response.json().then(json => {
                    let user = json.message[0];
                    $("#name").val(user.name);
                    $("#email").val(user.email);
                    $("#phone").val(formatPhoneNumber(user.phone));
                    closeLoading();
                });
            });
        }
        $("#modal").modal('show');
    }

    function resetForm() {
        $("#nameFilter").val('');
        $("#emailFilter").val('');
        index = 0;
        partial = 0;
        total = 1;
        $("#userTable tbody").empty();
        getUsers();
    }

    function changeMessageType(type, id) {
        let message = document.getElementById(id);
        if (type === 'ok') {
            message.classList.remove('alert-danger');
            message.classList.remove('d-none');
            message.classList.add('alert-info');
        }

        if (type === 'error') {
            message.classList.remove('alert-info');
            message.classList.remove('d-none');
            message.classList.add('alert-danger');
        }
    }

    function generateTableBody(json) {
        let icons = `<i class="fa fa-pencil text-info" title="Editar ${json.name}" onclick="openModal(${json.id})"></i> `;
        icons += `<i class="fa fa-times text-danger" title="Deletar ${json.name}" onclick="removeUser(${json.id})"></i> `;
        return `
            <tr>
                <td class="text-center"><img src="arquivos/${json.path}" width="40px" height="40px"></td>
                <td class="text-center">${json.name}</td>
                <td class="text-center">${json.email}</td>
                <td class="text-center">${formatPhoneNumber(json.phone)}</td>
                <td class="text-center">${icons}</td>
            </tr>
        `;
    }

    function filter() {
        $("#userTable tbody").empty();
        index = 0;
        total = 1;
        partial = 0;
        getUsers();
    }

    function formatPhoneNumber(phoneNumberString) {
        var cleaned = ('' + phoneNumberString).replace(/\D/g, '');
        var match = cleaned.match(/^(\d{2})(\d{5})(\d{4})$/);
        if (match) {
            return '(' + match[1] + ') ' + match[2] + '-' + match[3];
        }
        return '';
    }

    function getUsers() {
        showLoading();
        let name = $("#nameFilter").val();
        let email = $("#emailFilter").val();
        fetch(`<?= BASEURL ?>api/usuario/?name=${name}&email=${email}`, {
            method: 'GET',
            credentials: "same-origin",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                total = json.total;
                partial += json.partial;
                $("#total").text(total);
                $("#partial").text(partial);
                let users = json.message;
                let usersHtml = users.map(generateTableBody);
                $("#userTable tbody").append(usersHtml);
            });
        });
    }

    function removeUser(id) {
        showLoading();
        fetch(`<?= BASEURL ?>api/usuario/` + id, {
            method: 'DELETE',
            credentials: "same-origin",
            header: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            }
        }).then(response => {
            response.json().then(json => {
                closeLoading();
                changeMessageType(json.status, 'message');
                message.innerText = json.message;
                if(json.status == 'ok') filter();
            });
        });
    }

    $("#userForm").submit(function (e) {
        let divMessageForm = document.getElementById('message2');
        event.preventDefault();
        showLoading();
        $.ajax({
            type: 'POST',
            url: '<?= BASEURL ?>api/usuario/',
            data: new FormData(this),
            processData: false,
            contentType: false
        })
            .done(function (json) {
                closeLoading();
                divMessageForm.classList.add("alert-success");
                divMessageForm.classList.remove("alert-danger");
                divMessageForm.textContent = json.message;
                divMessageForm.classList.remove("d-none");
                $("#modal").modal('hide');
                filter();
            })
            .fail(function (json) {
                closeLoading();
                divMessageForm.classList.add("alert-danger");
                divMessageForm.classList.remove("alert-success");
                divMessageForm.textContent = json.responseJSON.message;
                divMessageForm.classList.remove("d-none");
            });
    });

    //form.addEventListener('submit', e => {
    //    e.preventDefault();
    //    showLoading();
    //    let formData = formDataToJson('userForm');
    //    let method = 'POST';
    //    if(formData.userId > 0) method = 'PUT';
    //    fetch(`<?//= BASEURL ?>//usuario/`, {
    //        method: 'POST',
    //        credentials: "same-origin",
    //        headers: {
    //            'Accept': 'application/json',
    //            'Content-Type': 'application/json',
    //        },
    //        body: JSON.stringify(formData),
    //    }).then(response => {
    //        response.json().then(json => {
    //            closeLoading();
    //            changeMessageType(json.status, 'message2');
    //            message2.innerText = json.message;
    //            if (json.status === 'ok') {
    //                $("#modal").modal('hide');
    //                filter();
    //            }
    //        });
    //    });
    //});

    $(document).ready(function () {
        getUsers();
    });

</script>